name = "font-generator-free"
compatibility_date = "2024-01-01"
workers_dev = false

[site]
bucket = "font-generator-free"

[env.production]
ENVIRONMENT = "production"

[[routes]]
pattern = "/*"
zone_id = "fontgeneratorfree.online"
